package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeCamioneta;
import org.oscarmorales.modelo.Camioneta;

/**
 * Ventana eliminar camioneta
 * @author Oscar
 */
public class VentanaEliminarCamioneta extends javax.swing.JInternalFrame {

    /**
     * Instancia eliminar camioneta
     */
    public ControlDeCamioneta controlador = ControlDeCamioneta.getInstanciaCamioneta();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaEliminarCamioneta() {
        initComponents();
    }
    
    Camioneta camionetaAEliminar = new Camioneta();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarCamioneta = new javax.swing.JPanel();
        panelTitleEliminarCamioneta = new javax.swing.JPanel();
        lblTitleEliminarCamioneta = new javax.swing.JLabel();
        lblCamionetaABuscarElimiNAR = new javax.swing.JLabel();
        btnEliminarCamioneta = new javax.swing.JButton();
        txtMotoABuscarCamioneta = new javax.swing.JTextField();
        btnMotoABuscarCamioneta = new javax.swing.JButton();
        txtModeloEliminarCamioneta = new javax.swing.JTextField();
        txtPlacaEliminarCamioneta = new javax.swing.JTextField();
        txtCombustibleEliminarCamioneta = new javax.swing.JTextField();
        txtMotorEliminarCamioneta = new javax.swing.JTextField();
        txtMarcaEliminarCamioneta = new javax.swing.JTextField();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaCamioneta = new javax.swing.JLabel();
        lblModeloCamioneta = new javax.swing.JLabel();
        lblPlacaCamioneta = new javax.swing.JLabel();
        lblCombustibleCamioneta = new javax.swing.JLabel();
        lblMotorCamioneta = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        panelEliminarCamioneta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarCamioneta.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelEliminarCamioneta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleEliminarCamioneta.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleEliminarCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleEliminarCamioneta.setText("ELIMINAR CAMIONETA");

        javax.swing.GroupLayout panelTitleEliminarCamionetaLayout = new javax.swing.GroupLayout(panelTitleEliminarCamioneta);
        panelTitleEliminarCamioneta.setLayout(panelTitleEliminarCamionetaLayout);
        panelTitleEliminarCamionetaLayout.setHorizontalGroup(
            panelTitleEliminarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarCamionetaLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleEliminarCamioneta)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        panelTitleEliminarCamionetaLayout.setVerticalGroup(
            panelTitleEliminarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarCamionetaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleEliminarCamioneta)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelEliminarCamioneta.add(panelTitleEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 100));

        lblCamionetaABuscarElimiNAR.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblCamionetaABuscarElimiNAR.setForeground(new java.awt.Color(255, 255, 255));
        lblCamionetaABuscarElimiNAR.setText("Ingrese placa de la camioneta a buscar");
        panelEliminarCamioneta.add(lblCamionetaABuscarElimiNAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 420, 60));

        btnEliminarCamioneta.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminarCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCamioneta.setText("ELIMINAR");
        btnEliminarCamioneta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminarCamioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCamionetaActionPerformed(evt);
            }
        });
        panelEliminarCamioneta.add(btnEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 190, 80));

        txtMotoABuscarCamioneta.setBackground(new java.awt.Color(255, 255, 255));
        txtMotoABuscarCamioneta.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMotoABuscarCamioneta.setForeground(new java.awt.Color(0, 0, 0));
        txtMotoABuscarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtMotoABuscarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 230, 40));

        btnMotoABuscarCamioneta.setBackground(new java.awt.Color(0, 102, 102));
        btnMotoABuscarCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnMotoABuscarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        btnMotoABuscarCamioneta.setText("BUSCAR");
        btnMotoABuscarCamioneta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMotoABuscarCamioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMotoABuscarCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoABuscarCamionetaActionPerformed(evt);
            }
        });
        panelEliminarCamioneta.add(btnMotoABuscarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 130, 40));

        txtModeloEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        txtModeloEliminarCamioneta.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtModeloEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        txtModeloEliminarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtModeloEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 230, 30));

        txtPlacaEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        txtPlacaEliminarCamioneta.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPlacaEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        txtPlacaEliminarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtPlacaEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 230, 30));

        txtCombustibleEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        txtCombustibleEliminarCamioneta.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtCombustibleEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        txtCombustibleEliminarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtCombustibleEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 230, 30));

        txtMotorEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        txtMotorEliminarCamioneta.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMotorEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        txtMotorEliminarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtMotorEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 230, 30));

        txtMarcaEliminarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        txtMarcaEliminarCamioneta.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMarcaEliminarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        txtMarcaEliminarCamioneta.setBorder(null);
        panelEliminarCamioneta.add(txtMarcaEliminarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 230, 30));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Datos de la camioneta que desea eliminar:");
        panelEliminarCamioneta.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 480, -1));

        lblMarcaCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaCamioneta.setText("Marca:");
        panelEliminarCamioneta.add(lblMarcaCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, -1));

        lblModeloCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloCamioneta.setText("Modelo:");
        panelEliminarCamioneta.add(lblModeloCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, -1));

        lblPlacaCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaCamioneta.setText("Placa:");
        panelEliminarCamioneta.add(lblPlacaCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 70, -1));

        lblCombustibleCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleCamioneta.setText("Combustible:");
        panelEliminarCamioneta.add(lblCombustibleCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, -1));

        lblMotorCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMotorCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblMotorCamioneta.setText("No. de asientos:");
        panelEliminarCamioneta.add(lblMotorCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotoABuscarCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoABuscarCamionetaActionPerformed
        // TODO add your handling code here:
        camionetaAEliminar = controlador.verCamioneta(txtMotoABuscarCamioneta.getText());
        txtMarcaEliminarCamioneta.setText(camionetaAEliminar.getMarca());
        txtModeloEliminarCamioneta.setText(camionetaAEliminar.getModelo());
        txtPlacaEliminarCamioneta.setText(camionetaAEliminar.getPlaca());
        txtCombustibleEliminarCamioneta.setText(camionetaAEliminar.getCombustible());
        txtMotorEliminarCamioneta.setText(String.valueOf(camionetaAEliminar.getAsientos()));        
    }//GEN-LAST:event_btnMotoABuscarCamionetaActionPerformed

    private void btnEliminarCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCamionetaActionPerformed
        // TODO add your handling code here:
        controlador.eliminarCamioneta(camionetaAEliminar);
        setVisible(false);
        txtMarcaEliminarCamioneta.setText("");
        txtModeloEliminarCamioneta.setText("");
        txtPlacaEliminarCamioneta.setText("");
        txtCombustibleEliminarCamioneta.setText("");
        txtMotoABuscarCamioneta.setText("");      
    }//GEN-LAST:event_btnEliminarCamionetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCamioneta;
    private javax.swing.JButton btnMotoABuscarCamioneta;
    private javax.swing.JLabel lblCamionetaABuscarElimiNAR;
    private javax.swing.JLabel lblCombustibleCamioneta;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaCamioneta;
    private javax.swing.JLabel lblModeloCamioneta;
    private javax.swing.JLabel lblMotorCamioneta;
    private javax.swing.JLabel lblPlacaCamioneta;
    private javax.swing.JLabel lblTitleEliminarCamioneta;
    private javax.swing.JPanel panelEliminarCamioneta;
    private javax.swing.JPanel panelTitleEliminarCamioneta;
    private javax.swing.JTextField txtCombustibleEliminarCamioneta;
    private javax.swing.JTextField txtMarcaEliminarCamioneta;
    private javax.swing.JTextField txtModeloEliminarCamioneta;
    private javax.swing.JTextField txtMotoABuscarCamioneta;
    private javax.swing.JTextField txtMotorEliminarCamioneta;
    private javax.swing.JTextField txtPlacaEliminarCamioneta;
    // End of variables declaration//GEN-END:variables
}
