package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeTrailer;
import org.oscarmorales.modelo.Trailer;

/**
 * Ventana actualizar trailer
 * @author Oscar
 */
public class VentanaActualizarTrailer extends javax.swing.JInternalFrame {

    /**
     * Instancia actualizar trailer
     */
    public ControlDeTrailer controlador = ControlDeTrailer.getInstanciaTrailer();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaActualizarTrailer() {
        initComponents();
    }
    
    Trailer trailerAntiguo = new Trailer();
    Trailer trailerActualizado = new Trailer();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarTrailer = new javax.swing.JPanel();
        panelTitleActualizarTrailer = new javax.swing.JPanel();
        lblTitleIAgregarTrailer = new javax.swing.JLabel();
        lblTrailerABuscar = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaTrailer = new javax.swing.JLabel();
        lblModeloTrailer = new javax.swing.JLabel();
        lblPlacaTrailer = new javax.swing.JLabel();
        lblCombustibleTrailer = new javax.swing.JLabel();
        lblToneladasTrailer = new javax.swing.JLabel();
        txtTrailerABuscar = new javax.swing.JTextField();
        txtMarcaActualizarTrailer = new javax.swing.JTextField();
        txtModeloActualizarTrailer = new javax.swing.JTextField();
        txtPlacaActualizarTrailer = new javax.swing.JTextField();
        txtCombustibleActualizarTrailer = new javax.swing.JTextField();
        txtToneladasActualizarTrailer = new javax.swing.JTextField();
        separatorActualizarTrailer = new javax.swing.JSeparator();
        btnTrailerABuscar = new javax.swing.JButton();
        btnActualizarTrailer = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelActualizarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        panelActualizarTrailer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelActualizarTrailer.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelActualizarTrailer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleActualizarTrailer.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarTrailer.setText("ACTUALIZAR TRAILER");

        javax.swing.GroupLayout panelTitleActualizarTrailerLayout = new javax.swing.GroupLayout(panelTitleActualizarTrailer);
        panelTitleActualizarTrailer.setLayout(panelTitleActualizarTrailerLayout);
        panelTitleActualizarTrailerLayout.setHorizontalGroup(
            panelTitleActualizarTrailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleActualizarTrailerLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleIAgregarTrailer)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        panelTitleActualizarTrailerLayout.setVerticalGroup(
            panelTitleActualizarTrailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleActualizarTrailerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleIAgregarTrailer)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelActualizarTrailer.add(panelTitleActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 100));

        lblTrailerABuscar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblTrailerABuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblTrailerABuscar.setText("Ingrese placa del trailer a buscar");
        panelActualizarTrailer.add(lblTrailerABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 250, -1));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Ingrese los datos actualizados del trailer");
        panelActualizarTrailer.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 310, -1));

        lblMarcaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaTrailer.setText("Marca");
        panelActualizarTrailer.add(lblMarcaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, -1));

        lblModeloTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloTrailer.setText("Modelo");
        panelActualizarTrailer.add(lblModeloTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 80, -1));

        lblPlacaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaTrailer.setText("Placa");
        panelActualizarTrailer.add(lblPlacaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 70, -1));

        lblCombustibleTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleTrailer.setText("Combustible");
        panelActualizarTrailer.add(lblCombustibleTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, -1));

        lblToneladasTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblToneladasTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblToneladasTrailer.setText("Toneladas");
        panelActualizarTrailer.add(lblToneladasTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 110, -1));

        txtTrailerABuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtTrailerABuscar.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtTrailerABuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtTrailerABuscar.setBorder(null);
        panelActualizarTrailer.add(txtTrailerABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 230, 30));

        txtMarcaActualizarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtMarcaActualizarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMarcaActualizarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaActualizarTrailer.setBorder(null);
        panelActualizarTrailer.add(txtMarcaActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 230, 30));

        txtModeloActualizarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloActualizarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtModeloActualizarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloActualizarTrailer.setBorder(null);
        panelActualizarTrailer.add(txtModeloActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 230, 30));

        txtPlacaActualizarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacaActualizarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtPlacaActualizarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacaActualizarTrailer.setBorder(null);
        panelActualizarTrailer.add(txtPlacaActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 230, 30));

        txtCombustibleActualizarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtCombustibleActualizarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtCombustibleActualizarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtCombustibleActualizarTrailer.setBorder(null);
        panelActualizarTrailer.add(txtCombustibleActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 230, 30));

        txtToneladasActualizarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtToneladasActualizarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtToneladasActualizarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtToneladasActualizarTrailer.setBorder(null);
        panelActualizarTrailer.add(txtToneladasActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 230, 30));
        panelActualizarTrailer.add(separatorActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1150, 20));

        btnTrailerABuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnTrailerABuscar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnTrailerABuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnTrailerABuscar.setText("BUSCAR");
        btnTrailerABuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnTrailerABuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrailerABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrailerABuscarActionPerformed(evt);
            }
        });
        panelActualizarTrailer.add(btnTrailerABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 110, 30));

        btnActualizarTrailer.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnActualizarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarTrailer.setText("ACTUALIZAR");
        btnActualizarTrailer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnActualizarTrailer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTrailerActionPerformed(evt);
            }
        });
        panelActualizarTrailer.add(btnActualizarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrailerABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrailerABuscarActionPerformed
        // TODO add your handling code here:
        trailerAntiguo = controlador.verTrailer(txtTrailerABuscar.getText());
        txtMarcaActualizarTrailer.setText(trailerAntiguo.getMarca());
        txtModeloActualizarTrailer.setText(trailerAntiguo.getModelo());
        txtPlacaActualizarTrailer.setText(trailerAntiguo.getPlaca());
        txtCombustibleActualizarTrailer.setText(trailerAntiguo.getCombustible());
        txtToneladasActualizarTrailer.setText(String.valueOf(trailerAntiguo.getToneladas()));
    }//GEN-LAST:event_btnTrailerABuscarActionPerformed

    private void btnActualizarTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTrailerActionPerformed
        // TODO add your handling code here:
        trailerActualizado.setMarca(txtMarcaActualizarTrailer.getText());
        trailerActualizado.setModelo(txtModeloActualizarTrailer.getText());
        trailerActualizado.setPlaca(txtPlacaActualizarTrailer.getText());
        trailerActualizado.setCombustible(txtCombustibleActualizarTrailer.getText());
        trailerActualizado.setToneladas(Integer.parseInt(txtToneladasActualizarTrailer.getText()));
        controlador.actualizarTrailer(trailerAntiguo, trailerActualizado);
        setVisible(false);
        txtMarcaActualizarTrailer.setText("");
        txtModeloActualizarTrailer.setText("");
        txtPlacaActualizarTrailer.setText("");
        txtCombustibleActualizarTrailer.setText("");
        txtToneladasActualizarTrailer.setText("");         
        txtTrailerABuscar.setText("");         
    }//GEN-LAST:event_btnActualizarTrailerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTrailer;
    private javax.swing.JButton btnTrailerABuscar;
    private javax.swing.JLabel lblCombustibleTrailer;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaTrailer;
    private javax.swing.JLabel lblModeloTrailer;
    private javax.swing.JLabel lblPlacaTrailer;
    private javax.swing.JLabel lblTitleIAgregarTrailer;
    private javax.swing.JLabel lblToneladasTrailer;
    private javax.swing.JLabel lblTrailerABuscar;
    private javax.swing.JPanel panelActualizarTrailer;
    private javax.swing.JPanel panelTitleActualizarTrailer;
    private javax.swing.JSeparator separatorActualizarTrailer;
    private javax.swing.JTextField txtCombustibleActualizarTrailer;
    private javax.swing.JTextField txtMarcaActualizarTrailer;
    private javax.swing.JTextField txtModeloActualizarTrailer;
    private javax.swing.JTextField txtPlacaActualizarTrailer;
    private javax.swing.JTextField txtToneladasActualizarTrailer;
    private javax.swing.JTextField txtTrailerABuscar;
    // End of variables declaration//GEN-END:variables
}
