/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.oscarmorales.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.oscarmorales.controlador.ControlDeCarro;
import org.oscarmorales.modelo.Carro;

/**
 * Ventana ver carro
 * @author Oscar
 */
public class VentanaVerCarro extends javax.swing.JInternalFrame {

    /**
     * Instancia ver carro
     */
    public ControlDeCarro controlador = ControlDeCarro.getInstanciaCarro();
    
    /**
     * Creates new form VentanaVerCarro
     */
    public VentanaVerCarro() {
        initComponents();
    }

    /**
     * Metodo mostrar carro
     */
    public void mostrarCarro(){
        String [] encabezados = {"Marca","Modelo","Placa","Combustible","No. de puertas"};
        int cantidadDeCarros = controlador.cantidadDeCarros();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeCarros);
        tablaDeCarro.setModel(cabecera);
        TableModel listaDeCarros = tablaDeCarro.getModel();
        
        for(int i=0; i<cantidadDeCarros; i++){
            Carro carro = controlador.mostrarCarros().get(i);
            listaDeCarros.setValueAt(carro.getMarca(), i, 0);
            listaDeCarros.setValueAt(carro.getModelo(), i, 1);
            listaDeCarros.setValueAt(carro.getPlaca(), i, 2);
            listaDeCarros.setValueAt(carro.getCombustible(), i, 3);
            listaDeCarros.setValueAt(carro.getPuertas(), i, 4);
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVistaVerCarro = new javax.swing.JScrollPane();
        tablaDeCarro = new javax.swing.JTable();
        panelTitleAgregarCarro = new javax.swing.JPanel();
        lblTitleIAgregarCarro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1164, 676));

        tablaDeCarro.setBackground(new java.awt.Color(51, 51, 51));
        tablaDeCarro.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tablaDeCarro.setForeground(new java.awt.Color(255, 255, 255));
        tablaDeCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Placa", "Combustible", "No. de puertas"
            }
        ));
        tablaDeCarro.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tablaDeCarro.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollPanelVistaVerCarro.setViewportView(tablaDeCarro);

        panelTitleAgregarCarro.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarCarro.setText("VER CARRO");

        javax.swing.GroupLayout panelTitleAgregarCarroLayout = new javax.swing.GroupLayout(panelTitleAgregarCarro);
        panelTitleAgregarCarro.setLayout(panelTitleAgregarCarroLayout);
        panelTitleAgregarCarroLayout.setHorizontalGroup(
            panelTitleAgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleAgregarCarroLayout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(lblTitleIAgregarCarro)
                .addGap(471, 471, 471))
        );
        panelTitleAgregarCarroLayout.setVerticalGroup(
            panelTitleAgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarCarroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleIAgregarCarro)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitleAgregarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelVistaVerCarro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitleAgregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelVistaVerCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitleIAgregarCarro;
    private javax.swing.JPanel panelTitleAgregarCarro;
    private javax.swing.JScrollPane scrollPanelVistaVerCarro;
    private javax.swing.JTable tablaDeCarro;
    // End of variables declaration//GEN-END:variables
}
