package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeMoto;
import org.oscarmorales.modelo.Moto;

/**
 * Ventana actualizar moto
 * @author Oscar
 */
public class VentanaActualizarMoto extends javax.swing.JInternalFrame {

    /**
     * Instancia actualizar moto
     */
    public ControlDeMoto controlador = ControlDeMoto.getInstanciaMoto();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaActualizarMoto() {
        initComponents();
    }
    
    Moto motoAntiguo = new Moto();
    Moto motoActualizado = new Moto();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActualizarMoto = new javax.swing.JPanel();
        panelTitleActualizarMoto = new javax.swing.JPanel();
        lblTitleIAgregarCarro = new javax.swing.JLabel();
        lblMotoABuscar = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaMoto = new javax.swing.JLabel();
        lblModeloMoto = new javax.swing.JLabel();
        lblPlacaMoto = new javax.swing.JLabel();
        lblCombustibleMoto = new javax.swing.JLabel();
        lblMotorMoto = new javax.swing.JLabel();
        txtMotoABuscar = new javax.swing.JTextField();
        txtMarcaActualizarMoto = new javax.swing.JTextField();
        txtModeloActualizarMoto = new javax.swing.JTextField();
        txtPlacaActualizarMoto = new javax.swing.JTextField();
        txtCombustibleActualizarMoto = new javax.swing.JTextField();
        txtMotorActualizarMoto = new javax.swing.JTextField();
        separatorActualizarMoto = new javax.swing.JSeparator();
        btnMotoABuscar = new javax.swing.JButton();
        btnActualizarMoto = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelActualizarMoto.setBackground(new java.awt.Color(51, 51, 51));
        panelActualizarMoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelActualizarMoto.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelActualizarMoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleActualizarMoto.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarCarro.setText("ACTUALIZAR MOTO");

        javax.swing.GroupLayout panelTitleActualizarMotoLayout = new javax.swing.GroupLayout(panelTitleActualizarMoto);
        panelTitleActualizarMoto.setLayout(panelTitleActualizarMotoLayout);
        panelTitleActualizarMotoLayout.setHorizontalGroup(
            panelTitleActualizarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleActualizarMotoLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleIAgregarCarro)
                .addContainerGap(401, Short.MAX_VALUE))
        );
        panelTitleActualizarMotoLayout.setVerticalGroup(
            panelTitleActualizarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleActualizarMotoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleIAgregarCarro)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelActualizarMoto.add(panelTitleActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 100));

        lblMotoABuscar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMotoABuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblMotoABuscar.setText("Ingrese placa de la moto a buscar");
        panelActualizarMoto.add(lblMotoABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 250, -1));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Ingrese los datos actualizados de la moto");
        panelActualizarMoto.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 310, -1));

        lblMarcaMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaMoto.setText("Marca");
        panelActualizarMoto.add(lblMarcaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, -1));

        lblModeloMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloMoto.setText("Modelo");
        panelActualizarMoto.add(lblModeloMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 80, -1));

        lblPlacaMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaMoto.setText("Placa");
        panelActualizarMoto.add(lblPlacaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 70, -1));

        lblCombustibleMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleMoto.setText("Combustible");
        panelActualizarMoto.add(lblCombustibleMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, -1));

        lblMotorMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMotorMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblMotorMoto.setText("Motor");
        panelActualizarMoto.add(lblMotorMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 110, -1));

        txtMotoABuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtMotoABuscar.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMotoABuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtMotoABuscar.setBorder(null);
        panelActualizarMoto.add(txtMotoABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 230, 30));

        txtMarcaActualizarMoto.setBackground(new java.awt.Color(255, 255, 255));
        txtMarcaActualizarMoto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMarcaActualizarMoto.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaActualizarMoto.setBorder(null);
        panelActualizarMoto.add(txtMarcaActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 230, 30));

        txtModeloActualizarMoto.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloActualizarMoto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtModeloActualizarMoto.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloActualizarMoto.setBorder(null);
        panelActualizarMoto.add(txtModeloActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 230, 30));

        txtPlacaActualizarMoto.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacaActualizarMoto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtPlacaActualizarMoto.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacaActualizarMoto.setBorder(null);
        panelActualizarMoto.add(txtPlacaActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 230, 30));

        txtCombustibleActualizarMoto.setBackground(new java.awt.Color(255, 255, 255));
        txtCombustibleActualizarMoto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtCombustibleActualizarMoto.setForeground(new java.awt.Color(0, 0, 0));
        txtCombustibleActualizarMoto.setBorder(null);
        panelActualizarMoto.add(txtCombustibleActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 230, 30));

        txtMotorActualizarMoto.setBackground(new java.awt.Color(255, 255, 255));
        txtMotorActualizarMoto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMotorActualizarMoto.setForeground(new java.awt.Color(0, 0, 0));
        txtMotorActualizarMoto.setBorder(null);
        panelActualizarMoto.add(txtMotorActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 230, 30));
        panelActualizarMoto.add(separatorActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1150, 20));

        btnMotoABuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnMotoABuscar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnMotoABuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnMotoABuscar.setText("BUSCAR");
        btnMotoABuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMotoABuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMotoABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoABuscarActionPerformed(evt);
            }
        });
        panelActualizarMoto.add(btnMotoABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 110, 30));

        btnActualizarMoto.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizarMoto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnActualizarMoto.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarMoto.setText("ACTUALIZAR");
        btnActualizarMoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnActualizarMoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMotoActionPerformed(evt);
            }
        });
        panelActualizarMoto.add(btnActualizarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActualizarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotoABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoABuscarActionPerformed
        // TODO add your handling code here:
        motoAntiguo = controlador.verMoto(txtMotoABuscar.getText());
        txtMarcaActualizarMoto.setText(motoAntiguo.getMarca());
        txtModeloActualizarMoto.setText(motoAntiguo.getModelo());
        txtPlacaActualizarMoto.setText(motoAntiguo.getPlaca());
        txtCombustibleActualizarMoto.setText(motoAntiguo.getCombustible());
        txtMotorActualizarMoto.setText(String.valueOf(motoAntiguo.getMotor()));
    }//GEN-LAST:event_btnMotoABuscarActionPerformed

    private void btnActualizarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMotoActionPerformed
        // TODO add your handling code here:
        motoActualizado.setMarca(txtMarcaActualizarMoto.getText());
        motoActualizado.setModelo(txtModeloActualizarMoto.getText());
        motoActualizado.setPlaca(txtPlacaActualizarMoto.getText());
        motoActualizado.setCombustible(txtCombustibleActualizarMoto.getText());
        motoActualizado.setMotor(Integer.parseInt(txtMotorActualizarMoto.getText()));
        controlador.actualizarMoto(motoAntiguo, motoActualizado);
        setVisible(false);
        txtMarcaActualizarMoto.setText("");
        txtModeloActualizarMoto.setText("");
        txtPlacaActualizarMoto.setText("");
        txtCombustibleActualizarMoto.setText("");
        txtMotorActualizarMoto.setText("");         
        txtMotoABuscar.setText("");         
    }//GEN-LAST:event_btnActualizarMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMoto;
    private javax.swing.JButton btnMotoABuscar;
    private javax.swing.JLabel lblCombustibleMoto;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaMoto;
    private javax.swing.JLabel lblModeloMoto;
    private javax.swing.JLabel lblMotoABuscar;
    private javax.swing.JLabel lblMotorMoto;
    private javax.swing.JLabel lblPlacaMoto;
    private javax.swing.JLabel lblTitleIAgregarCarro;
    private javax.swing.JPanel panelActualizarMoto;
    private javax.swing.JPanel panelTitleActualizarMoto;
    private javax.swing.JSeparator separatorActualizarMoto;
    private javax.swing.JTextField txtCombustibleActualizarMoto;
    private javax.swing.JTextField txtMarcaActualizarMoto;
    private javax.swing.JTextField txtModeloActualizarMoto;
    private javax.swing.JTextField txtMotoABuscar;
    private javax.swing.JTextField txtMotorActualizarMoto;
    private javax.swing.JTextField txtPlacaActualizarMoto;
    // End of variables declaration//GEN-END:variables
}
