/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeTrailer;
import org.oscarmorales.modelo.Trailer;

/**
 * Ventana eliminar trailer
 * @author Oscar
 */
public class VentanaEliminarTrailer extends javax.swing.JInternalFrame {

    /**
     * Instancia eliminar trailer
     */
    public ControlDeTrailer controlador = ControlDeTrailer.getInstanciaTrailer();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaEliminarTrailer() {
        initComponents();
    }
    
    Trailer trailerAEliminar = new Trailer();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarTrailer = new javax.swing.JPanel();
        panelTitleEliminarTrailer = new javax.swing.JPanel();
        lblTitleEliminarTrailer = new javax.swing.JLabel();
        lblCamionetaABuscarTrailer = new javax.swing.JLabel();
        btnEliminarTrailer = new javax.swing.JButton();
        txtMotoABuscarTrailer = new javax.swing.JTextField();
        btnMotoABuscarTrailer = new javax.swing.JButton();
        txtModeloEliminarTrailer = new javax.swing.JTextField();
        txtPlacaEliminarTrailer = new javax.swing.JTextField();
        txtToneladasEliminarTrailer = new javax.swing.JTextField();
        txtMarcaEliminarTrailer = new javax.swing.JTextField();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaTrailer = new javax.swing.JLabel();
        lblModeloTrailer = new javax.swing.JLabel();
        lblPlacaTrailer = new javax.swing.JLabel();
        lblCombustibleTrailer = new javax.swing.JLabel();
        lblMotorTrailer = new javax.swing.JLabel();
        txtCombustibleEliminarTrailer = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        panelEliminarTrailer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarTrailer.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelEliminarTrailer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleEliminarTrailer.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleEliminarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleEliminarTrailer.setText("ELIMINAR TRAILER");

        javax.swing.GroupLayout panelTitleEliminarTrailerLayout = new javax.swing.GroupLayout(panelTitleEliminarTrailer);
        panelTitleEliminarTrailer.setLayout(panelTitleEliminarTrailerLayout);
        panelTitleEliminarTrailerLayout.setHorizontalGroup(
            panelTitleEliminarTrailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarTrailerLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleEliminarTrailer)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        panelTitleEliminarTrailerLayout.setVerticalGroup(
            panelTitleEliminarTrailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarTrailerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleEliminarTrailer)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelEliminarTrailer.add(panelTitleEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 100));

        lblCamionetaABuscarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblCamionetaABuscarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblCamionetaABuscarTrailer.setText("Ingrese placa del trailer a buscar");
        panelEliminarTrailer.add(lblCamionetaABuscarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 420, 60));

        btnEliminarTrailer.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTrailer.setText("ELIMINAR");
        btnEliminarTrailer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminarTrailer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTrailerActionPerformed(evt);
            }
        });
        panelEliminarTrailer.add(btnEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 190, 80));

        txtMotoABuscarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtMotoABuscarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMotoABuscarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtMotoABuscarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtMotoABuscarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 230, 40));

        btnMotoABuscarTrailer.setBackground(new java.awt.Color(0, 102, 102));
        btnMotoABuscarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnMotoABuscarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        btnMotoABuscarTrailer.setText("BUSCAR");
        btnMotoABuscarTrailer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMotoABuscarTrailer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMotoABuscarTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoABuscarTrailerActionPerformed(evt);
            }
        });
        panelEliminarTrailer.add(btnMotoABuscarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 130, 40));

        txtModeloEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        txtModeloEliminarTrailer.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtModeloEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        txtModeloEliminarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtModeloEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 230, 30));

        txtPlacaEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        txtPlacaEliminarTrailer.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPlacaEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        txtPlacaEliminarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtPlacaEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 230, 30));

        txtToneladasEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        txtToneladasEliminarTrailer.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtToneladasEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        txtToneladasEliminarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtToneladasEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 230, 30));

        txtMarcaEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        txtMarcaEliminarTrailer.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMarcaEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        txtMarcaEliminarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtMarcaEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 230, 30));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Datos del trailer que desea eliminar:");
        panelEliminarTrailer.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 480, -1));

        lblMarcaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaTrailer.setText("Marca:");
        panelEliminarTrailer.add(lblMarcaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, -1));

        lblModeloTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloTrailer.setText("Modelo:");
        panelEliminarTrailer.add(lblModeloTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, -1));

        lblPlacaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaTrailer.setText("Placa:");
        panelEliminarTrailer.add(lblPlacaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 70, -1));

        lblCombustibleTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleTrailer.setText("Combustible:");
        panelEliminarTrailer.add(lblCombustibleTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, -1));

        lblMotorTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMotorTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblMotorTrailer.setText("Toneladas:");
        panelEliminarTrailer.add(lblMotorTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 150, -1));

        txtCombustibleEliminarTrailer.setBackground(new java.awt.Color(51, 51, 51));
        txtCombustibleEliminarTrailer.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtCombustibleEliminarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        txtCombustibleEliminarTrailer.setBorder(null);
        panelEliminarTrailer.add(txtCombustibleEliminarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotoABuscarTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoABuscarTrailerActionPerformed
        // TODO add your handling code here:
        trailerAEliminar = controlador.verTrailer(txtMotoABuscarTrailer.getText());
        txtMarcaEliminarTrailer.setText(trailerAEliminar.getMarca());
        txtModeloEliminarTrailer.setText(trailerAEliminar.getModelo());
        txtPlacaEliminarTrailer.setText(trailerAEliminar.getPlaca());
        txtCombustibleEliminarTrailer.setText(trailerAEliminar.getCombustible());
        txtToneladasEliminarTrailer.setText(String.valueOf(trailerAEliminar.getToneladas()));        
    }//GEN-LAST:event_btnMotoABuscarTrailerActionPerformed

    private void btnEliminarTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTrailerActionPerformed
        // TODO add your handling code here:
        controlador.eliminarTrailer(trailerAEliminar);
        setVisible(false);
        txtMarcaEliminarTrailer.setText("");
        txtModeloEliminarTrailer.setText("");
        txtPlacaEliminarTrailer.setText("");
        txtCombustibleEliminarTrailer.setText("");
        txtToneladasEliminarTrailer.setText("");         
        txtMotoABuscarTrailer.setText("");      
    }//GEN-LAST:event_btnEliminarTrailerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarTrailer;
    private javax.swing.JButton btnMotoABuscarTrailer;
    private javax.swing.JLabel lblCamionetaABuscarTrailer;
    private javax.swing.JLabel lblCombustibleTrailer;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaTrailer;
    private javax.swing.JLabel lblModeloTrailer;
    private javax.swing.JLabel lblMotorTrailer;
    private javax.swing.JLabel lblPlacaTrailer;
    private javax.swing.JLabel lblTitleEliminarTrailer;
    private javax.swing.JPanel panelEliminarTrailer;
    private javax.swing.JPanel panelTitleEliminarTrailer;
    private javax.swing.JTextField txtCombustibleEliminarTrailer;
    private javax.swing.JTextField txtMarcaEliminarTrailer;
    private javax.swing.JTextField txtModeloEliminarTrailer;
    private javax.swing.JTextField txtMotoABuscarTrailer;
    private javax.swing.JTextField txtPlacaEliminarTrailer;
    private javax.swing.JTextField txtToneladasEliminarTrailer;
    // End of variables declaration//GEN-END:variables
}
