package org.oscarmorales.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.oscarmorales.controlador.ControlDeMoto;
import org.oscarmorales.modelo.Moto;

/**
 * Ventana ver moto
 * @author Oscar
 */
public class VentanaVerMoto extends javax.swing.JInternalFrame {

    /**
     * Instancia ver moto
     */
    public ControlDeMoto controlador = ControlDeMoto.getInstanciaMoto();
    
    /**
     * Creates new form VentanaVerCarro
     */
    public VentanaVerMoto() {
        initComponents();
    }

    /**
     * Metodo mostrar moto
     */
    public void mostrarMoto(){
        String [] encabezados = {"Marca","Modelo","Placa","Combustible", "Motor"};
        int cantidadDeMotos = controlador.cantidadDeMotos();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeMotos);
        tablaDeMoto.setModel(cabecera);
        TableModel listaDeMotos = tablaDeMoto.getModel();
        for(int i=0; i<cantidadDeMotos; i++){
            Moto moto = controlador.mostrarMotos().get(i);
            listaDeMotos.setValueAt(moto.getMarca(), i, 0);
            listaDeMotos.setValueAt(moto.getModelo(), i, 1);
            listaDeMotos.setValueAt(moto.getPlaca(), i, 2);
            listaDeMotos.setValueAt(moto.getCombustible(), i, 3);
            listaDeMotos.setValueAt(moto.getMotor(), i, 4);
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVistaVerMoto = new javax.swing.JScrollPane();
        tablaDeMoto = new javax.swing.JTable();
        panelTitleAgregarMoto = new javax.swing.JPanel();
        lblTitleIAgregarMoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1164, 676));

        tablaDeMoto.setBackground(new java.awt.Color(51, 51, 51));
        tablaDeMoto.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tablaDeMoto.setForeground(new java.awt.Color(255, 255, 255));
        tablaDeMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Placa", "Combustible", "Motor"
            }
        ));
        tablaDeMoto.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tablaDeMoto.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollPanelVistaVerMoto.setViewportView(tablaDeMoto);

        panelTitleAgregarMoto.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarMoto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarMoto.setText("VER MOTO");

        javax.swing.GroupLayout panelTitleAgregarMotoLayout = new javax.swing.GroupLayout(panelTitleAgregarMoto);
        panelTitleAgregarMoto.setLayout(panelTitleAgregarMotoLayout);
        panelTitleAgregarMotoLayout.setHorizontalGroup(
            panelTitleAgregarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleAgregarMotoLayout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(lblTitleIAgregarMoto)
                .addGap(479, 479, 479))
        );
        panelTitleAgregarMotoLayout.setVerticalGroup(
            panelTitleAgregarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarMotoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitleIAgregarMoto)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitleAgregarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelVistaVerMoto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitleAgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelVistaVerMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitleIAgregarMoto;
    private javax.swing.JPanel panelTitleAgregarMoto;
    private javax.swing.JScrollPane scrollPanelVistaVerMoto;
    private javax.swing.JTable tablaDeMoto;
    // End of variables declaration//GEN-END:variables
}
