/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeMoto;
import org.oscarmorales.modelo.Moto;

/**
 * Ventana eliminar moto
 * @author Oscar
 */
public class VentanaEliminarMoto extends javax.swing.JInternalFrame {

    /**
     * Instancia eliminar moto
     */
    public ControlDeMoto controlador = ControlDeMoto.getInstanciaMoto();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaEliminarMoto() {
        initComponents();
    }
    
    Moto motoAEliminar = new Moto();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarMoto = new javax.swing.JPanel();
        panelTitleEliminarMoto = new javax.swing.JPanel();
        lblTitleEliminarMoto = new javax.swing.JLabel();
        lblMotoABuscarElimiNAR = new javax.swing.JLabel();
        btnEliminarMoto = new javax.swing.JButton();
        txtMotoABuscarEliminar = new javax.swing.JTextField();
        btnMotoABuscarEliminar = new javax.swing.JButton();
        txtModeloEliminarMoto = new javax.swing.JTextField();
        txtPlacaEliminarMoto = new javax.swing.JTextField();
        txtCombustibleEliminarMoto = new javax.swing.JTextField();
        txtMotorEliminarMoto = new javax.swing.JTextField();
        txtMarcaEliminarMoto = new javax.swing.JTextField();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaMoto = new javax.swing.JLabel();
        lblModeloMoto = new javax.swing.JLabel();
        lblPlacaMoto = new javax.swing.JLabel();
        lblCombustibleMoto = new javax.swing.JLabel();
        lblMotorMoto = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        panelEliminarMoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarMoto.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelEliminarMoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleEliminarMoto.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleEliminarMoto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleEliminarMoto.setText("ELIMINAR MOTO");

        javax.swing.GroupLayout panelTitleEliminarMotoLayout = new javax.swing.GroupLayout(panelTitleEliminarMoto);
        panelTitleEliminarMoto.setLayout(panelTitleEliminarMotoLayout);
        panelTitleEliminarMotoLayout.setHorizontalGroup(
            panelTitleEliminarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarMotoLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleEliminarMoto)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        panelTitleEliminarMotoLayout.setVerticalGroup(
            panelTitleEliminarMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarMotoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleEliminarMoto)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelEliminarMoto.add(panelTitleEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 100));

        lblMotoABuscarElimiNAR.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblMotoABuscarElimiNAR.setForeground(new java.awt.Color(255, 255, 255));
        lblMotoABuscarElimiNAR.setText("Ingrese placa de la moto a buscar");
        panelEliminarMoto.add(lblMotoABuscarElimiNAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 380, 60));

        btnEliminarMoto.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminarMoto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMoto.setText("ELIMINAR");
        btnEliminarMoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminarMoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMotoActionPerformed(evt);
            }
        });
        panelEliminarMoto.add(btnEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 190, 80));

        txtMotoABuscarEliminar.setBackground(new java.awt.Color(255, 255, 255));
        txtMotoABuscarEliminar.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMotoABuscarEliminar.setForeground(new java.awt.Color(0, 0, 0));
        txtMotoABuscarEliminar.setBorder(null);
        panelEliminarMoto.add(txtMotoABuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 230, 40));

        btnMotoABuscarEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnMotoABuscarEliminar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnMotoABuscarEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnMotoABuscarEliminar.setText("BUSCAR");
        btnMotoABuscarEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMotoABuscarEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMotoABuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoABuscarEliminarActionPerformed(evt);
            }
        });
        panelEliminarMoto.add(btnMotoABuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 130, 40));

        txtModeloEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        txtModeloEliminarMoto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtModeloEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        txtModeloEliminarMoto.setBorder(null);
        panelEliminarMoto.add(txtModeloEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 230, 30));

        txtPlacaEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        txtPlacaEliminarMoto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPlacaEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        txtPlacaEliminarMoto.setBorder(null);
        panelEliminarMoto.add(txtPlacaEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 230, 30));

        txtCombustibleEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        txtCombustibleEliminarMoto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtCombustibleEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        txtCombustibleEliminarMoto.setBorder(null);
        panelEliminarMoto.add(txtCombustibleEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 230, 30));

        txtMotorEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        txtMotorEliminarMoto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMotorEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        txtMotorEliminarMoto.setBorder(null);
        panelEliminarMoto.add(txtMotorEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 230, 30));

        txtMarcaEliminarMoto.setBackground(new java.awt.Color(51, 51, 51));
        txtMarcaEliminarMoto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMarcaEliminarMoto.setForeground(new java.awt.Color(255, 255, 255));
        txtMarcaEliminarMoto.setBorder(null);
        panelEliminarMoto.add(txtMarcaEliminarMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 230, 30));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Datos de la moto que desea eliminar:");
        panelEliminarMoto.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 430, -1));

        lblMarcaMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaMoto.setText("Marca:");
        panelEliminarMoto.add(lblMarcaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, -1));

        lblModeloMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloMoto.setText("Modelo:");
        panelEliminarMoto.add(lblModeloMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, -1));

        lblPlacaMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaMoto.setText("Placa:");
        panelEliminarMoto.add(lblPlacaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 70, -1));

        lblCombustibleMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleMoto.setText("Combustible:");
        panelEliminarMoto.add(lblCombustibleMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, -1));

        lblMotorMoto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMotorMoto.setForeground(new java.awt.Color(255, 255, 255));
        lblMotorMoto.setText("Motor:");
        panelEliminarMoto.add(lblMotorMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotoABuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoABuscarEliminarActionPerformed
        // TODO add your handling code here:
        motoAEliminar = controlador.verMoto(txtMotoABuscarEliminar.getText());
        txtMarcaEliminarMoto.setText(motoAEliminar.getMarca());
        txtModeloEliminarMoto.setText(motoAEliminar.getModelo());
        txtPlacaEliminarMoto.setText(motoAEliminar.getPlaca());
        txtCombustibleEliminarMoto.setText(motoAEliminar.getCombustible());
        txtMotorEliminarMoto.setText(String.valueOf(motoAEliminar.getMotor()));        
    }//GEN-LAST:event_btnMotoABuscarEliminarActionPerformed

    private void btnEliminarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMotoActionPerformed
        // TODO add your handling code here:
        controlador.eliminarMoto(motoAEliminar);
        setVisible(false);
        txtMarcaEliminarMoto.setText("");
        txtModeloEliminarMoto.setText("");
        txtPlacaEliminarMoto.setText("");
        txtCombustibleEliminarMoto.setText("");
        txtMotorEliminarMoto.setText("");         
        txtMotoABuscarEliminar.setText("");      
    }//GEN-LAST:event_btnEliminarMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMoto;
    private javax.swing.JButton btnMotoABuscarEliminar;
    private javax.swing.JLabel lblCombustibleMoto;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaMoto;
    private javax.swing.JLabel lblModeloMoto;
    private javax.swing.JLabel lblMotoABuscarElimiNAR;
    private javax.swing.JLabel lblMotorMoto;
    private javax.swing.JLabel lblPlacaMoto;
    private javax.swing.JLabel lblTitleEliminarMoto;
    private javax.swing.JPanel panelEliminarMoto;
    private javax.swing.JPanel panelTitleEliminarMoto;
    private javax.swing.JTextField txtCombustibleEliminarMoto;
    private javax.swing.JTextField txtMarcaEliminarMoto;
    private javax.swing.JTextField txtModeloEliminarMoto;
    private javax.swing.JTextField txtMotoABuscarEliminar;
    private javax.swing.JTextField txtMotorEliminarMoto;
    private javax.swing.JTextField txtPlacaEliminarMoto;
    // End of variables declaration//GEN-END:variables
}
