package org.oscarmorales.vista;

import java.awt.Color;
import org.oscarmorales.controlador.ControlDeCarro;
import org.oscarmorales.modelo.Carro;

/**
 * Ventana agregar carro
 * @author Oscar
 */
public class VentanaAgregarCarro extends javax.swing.JInternalFrame {
    
    /**
     * Instancia agregar carro
     */
    public ControlDeCarro controlador = ControlDeCarro.getInstanciaCarro();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaAgregarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarCarro = new javax.swing.JPanel();
        panelTitleAgregarCarro = new javax.swing.JPanel();
        lblTitleIAgregarCarro = new javax.swing.JLabel();
        lblMarcaCarro = new javax.swing.JLabel();
        lblModeloCarro = new javax.swing.JLabel();
        lblPlacaCarro = new javax.swing.JLabel();
        lblCombustibleCarro = new javax.swing.JLabel();
        lblPuertasCarro = new javax.swing.JLabel();
        txtMarcaAgregarCarro = new javax.swing.JTextField();
        txtModeloAgregarCarro = new javax.swing.JTextField();
        txtPlacaAgregarCarro = new javax.swing.JTextField();
        txtCombustibleAgregarCarro = new javax.swing.JTextField();
        txtPuertasAgregarCarro = new javax.swing.JTextField();
        separatorAgregarCarro = new javax.swing.JSeparator();
        btnAgregarCarro = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelAgregarCarro.setBackground(new java.awt.Color(51, 51, 51));
        panelAgregarCarro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgregarCarro.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelAgregarCarro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleAgregarCarro.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarCarro.setText("INGRESAR CARRO");

        javax.swing.GroupLayout panelTitleAgregarCarroLayout = new javax.swing.GroupLayout(panelTitleAgregarCarro);
        panelTitleAgregarCarro.setLayout(panelTitleAgregarCarroLayout);
        panelTitleAgregarCarroLayout.setHorizontalGroup(
            panelTitleAgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarCarroLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleIAgregarCarro)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        panelTitleAgregarCarroLayout.setVerticalGroup(
            panelTitleAgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarCarroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleIAgregarCarro)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelAgregarCarro.add(panelTitleAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 100));

        lblMarcaCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaCarro.setText("Marca");
        panelAgregarCarro.add(lblMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 80, -1));

        lblModeloCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloCarro.setText("Modelo");
        panelAgregarCarro.add(lblModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 80, -1));

        lblPlacaCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaCarro.setText("Placa");
        panelAgregarCarro.add(lblPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, -1));

        lblCombustibleCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleCarro.setText("Combustible");
        panelAgregarCarro.add(lblCombustibleCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 100, -1));

        lblPuertasCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPuertasCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblPuertasCarro.setText("No. de puertas");
        panelAgregarCarro.add(lblPuertasCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 110, -1));

        txtMarcaAgregarCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtMarcaAgregarCarro.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMarcaAgregarCarro.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaAgregarCarro.setBorder(null);
        panelAgregarCarro.add(txtMarcaAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 230, 30));

        txtModeloAgregarCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloAgregarCarro.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtModeloAgregarCarro.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloAgregarCarro.setBorder(null);
        panelAgregarCarro.add(txtModeloAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 230, 30));

        txtPlacaAgregarCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacaAgregarCarro.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtPlacaAgregarCarro.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacaAgregarCarro.setBorder(null);
        panelAgregarCarro.add(txtPlacaAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 230, 30));

        txtCombustibleAgregarCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtCombustibleAgregarCarro.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtCombustibleAgregarCarro.setForeground(new java.awt.Color(0, 0, 0));
        txtCombustibleAgregarCarro.setBorder(null);
        panelAgregarCarro.add(txtCombustibleAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 230, 30));

        txtPuertasAgregarCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtPuertasAgregarCarro.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtPuertasAgregarCarro.setForeground(new java.awt.Color(0, 0, 0));
        txtPuertasAgregarCarro.setBorder(null);
        panelAgregarCarro.add(txtPuertasAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 230, 30));
        panelAgregarCarro.add(separatorAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1150, 30));

        btnAgregarCarro.setBackground(new java.awt.Color(0, 102, 102));
        btnAgregarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnAgregarCarro.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCarro.setText("GUARDAR");
        btnAgregarCarro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarroActionPerformed(evt);
            }
        });
        panelAgregarCarro.add(btnAgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarroActionPerformed
        // TODO add your handling code here:
        Carro carro = new Carro();
        carro.setMarca(txtMarcaAgregarCarro.getText());
        carro.setModelo(txtModeloAgregarCarro.getText());
        carro.setPlaca(txtPlacaAgregarCarro.getText());
        carro.setCombustible(txtCombustibleAgregarCarro.getText());
        carro.setPuertas(Integer.parseInt(txtPuertasAgregarCarro.getText()));
        controlador.agregarCarro(carro);
        setVisible(false);
        txtMarcaAgregarCarro.setText("");
        txtModeloAgregarCarro.setText("");
        txtPlacaAgregarCarro.setText("");
        txtCombustibleAgregarCarro.setText("");
        txtPuertasAgregarCarro.setText("");        
    }//GEN-LAST:event_btnAgregarCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarro;
    private javax.swing.JLabel lblCombustibleCarro;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JLabel lblPuertasCarro;
    private javax.swing.JLabel lblTitleIAgregarCarro;
    private javax.swing.JPanel panelAgregarCarro;
    private javax.swing.JPanel panelTitleAgregarCarro;
    private javax.swing.JSeparator separatorAgregarCarro;
    private javax.swing.JTextField txtCombustibleAgregarCarro;
    private javax.swing.JTextField txtMarcaAgregarCarro;
    private javax.swing.JTextField txtModeloAgregarCarro;
    private javax.swing.JTextField txtPlacaAgregarCarro;
    private javax.swing.JTextField txtPuertasAgregarCarro;
    // End of variables declaration//GEN-END:variables
}
