/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.oscarmorales.vista;

import java.awt.Color;
import org.oscarmorales.controlador.ControlDeTrailer;
import org.oscarmorales.modelo.Trailer;

/**
 * Ventana agregar trailer
 * @author Oscar
 */
public class VentanaAgregarTrailer extends javax.swing.JInternalFrame {

    /**
     * Instancia agregar trailer
     */
    public ControlDeTrailer controlador = ControlDeTrailer.getInstanciaTrailer();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaAgregarTrailer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarCamioneta = new javax.swing.JPanel();
        panelTitleAgregarCamioneta = new javax.swing.JPanel();
        lblTitleIAgregarCamioneta = new javax.swing.JLabel();
        lblMarcaTrailer = new javax.swing.JLabel();
        lblModeloTrailer = new javax.swing.JLabel();
        lblPlacaTrailer = new javax.swing.JLabel();
        lblCombustibleTrailer = new javax.swing.JLabel();
        lblAsientosTrailer = new javax.swing.JLabel();
        txtMarcaAgregarTrailer = new javax.swing.JTextField();
        txtModeloAgregarTrailer = new javax.swing.JTextField();
        txtPlacaAgregarTrailer = new javax.swing.JTextField();
        txtCombustibleAgregarTrailer = new javax.swing.JTextField();
        txtToneladasAgregarTrailer = new javax.swing.JTextField();
        separatorAgregarTrailer = new javax.swing.JSeparator();
        btnAgregarTrailer = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelAgregarCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        panelAgregarCamioneta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAgregarCamioneta.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelAgregarCamioneta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleAgregarCamioneta.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarCamioneta.setText("INGRESAR TRAILER");

        javax.swing.GroupLayout panelTitleAgregarCamionetaLayout = new javax.swing.GroupLayout(panelTitleAgregarCamioneta);
        panelTitleAgregarCamioneta.setLayout(panelTitleAgregarCamionetaLayout);
        panelTitleAgregarCamionetaLayout.setHorizontalGroup(
            panelTitleAgregarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleAgregarCamionetaLayout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(lblTitleIAgregarCamioneta)
                .addGap(350, 350, 350))
        );
        panelTitleAgregarCamionetaLayout.setVerticalGroup(
            panelTitleAgregarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarCamionetaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitleIAgregarCamioneta)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelAgregarCamioneta.add(panelTitleAgregarCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 100));

        lblMarcaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaTrailer.setText("Marca");
        panelAgregarCamioneta.add(lblMarcaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 80, -1));

        lblModeloTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloTrailer.setText("Modelo");
        panelAgregarCamioneta.add(lblModeloTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 80, -1));

        lblPlacaTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaTrailer.setText("Placa");
        panelAgregarCamioneta.add(lblPlacaTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, -1));

        lblCombustibleTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleTrailer.setText("Combustible");
        panelAgregarCamioneta.add(lblCombustibleTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 100, -1));

        lblAsientosTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblAsientosTrailer.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientosTrailer.setText("Toneladas");
        panelAgregarCamioneta.add(lblAsientosTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 120, -1));

        txtMarcaAgregarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtMarcaAgregarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtMarcaAgregarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaAgregarTrailer.setBorder(null);
        panelAgregarCamioneta.add(txtMarcaAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 230, 30));

        txtModeloAgregarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloAgregarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtModeloAgregarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloAgregarTrailer.setBorder(null);
        panelAgregarCamioneta.add(txtModeloAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 230, 30));

        txtPlacaAgregarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacaAgregarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtPlacaAgregarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacaAgregarTrailer.setBorder(null);
        panelAgregarCamioneta.add(txtPlacaAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 230, 30));

        txtCombustibleAgregarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtCombustibleAgregarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtCombustibleAgregarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtCombustibleAgregarTrailer.setBorder(null);
        panelAgregarCamioneta.add(txtCombustibleAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 230, 30));

        txtToneladasAgregarTrailer.setBackground(new java.awt.Color(255, 255, 255));
        txtToneladasAgregarTrailer.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtToneladasAgregarTrailer.setForeground(new java.awt.Color(0, 0, 0));
        txtToneladasAgregarTrailer.setBorder(null);
        panelAgregarCamioneta.add(txtToneladasAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 230, 30));
        panelAgregarCamioneta.add(separatorAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1150, 30));

        btnAgregarTrailer.setBackground(new java.awt.Color(0, 102, 102));
        btnAgregarTrailer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnAgregarTrailer.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarTrailer.setText("GUARDAR");
        btnAgregarTrailer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregarTrailer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTrailerActionPerformed(evt);
            }
        });
        panelAgregarCamioneta.add(btnAgregarTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTrailerActionPerformed
        // TODO add your handling code here:
        Trailer trailer = new Trailer();
        trailer.setMarca(txtMarcaAgregarTrailer.getText());
        trailer.setModelo(txtModeloAgregarTrailer.getText());
        trailer.setPlaca(txtPlacaAgregarTrailer.getText());
        trailer.setCombustible(txtCombustibleAgregarTrailer.getText());
        trailer.setToneladas(Integer.parseInt(txtToneladasAgregarTrailer.getText()));
        controlador.agregarTrailer(trailer);
        setVisible(false);
        txtMarcaAgregarTrailer.setText("");
        txtModeloAgregarTrailer.setText("");
        txtPlacaAgregarTrailer.setText("");
        txtCombustibleAgregarTrailer.setText("");
        txtToneladasAgregarTrailer.setText("");        
    }//GEN-LAST:event_btnAgregarTrailerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTrailer;
    private javax.swing.JLabel lblAsientosTrailer;
    private javax.swing.JLabel lblCombustibleTrailer;
    private javax.swing.JLabel lblMarcaTrailer;
    private javax.swing.JLabel lblModeloTrailer;
    private javax.swing.JLabel lblPlacaTrailer;
    private javax.swing.JLabel lblTitleIAgregarCamioneta;
    private javax.swing.JPanel panelAgregarCamioneta;
    private javax.swing.JPanel panelTitleAgregarCamioneta;
    private javax.swing.JSeparator separatorAgregarTrailer;
    private javax.swing.JTextField txtCombustibleAgregarTrailer;
    private javax.swing.JTextField txtMarcaAgregarTrailer;
    private javax.swing.JTextField txtModeloAgregarTrailer;
    private javax.swing.JTextField txtPlacaAgregarTrailer;
    private javax.swing.JTextField txtToneladasAgregarTrailer;
    // End of variables declaration//GEN-END:variables
}
