/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.oscarmorales.vista;

import javax.swing.JOptionPane;
import org.oscarmorales.controlador.ControlDeCarro;
import org.oscarmorales.modelo.Carro;

/**
 * Ventana eliminar carro
 * @author Oscar
 */
public class VentanaEliminarCarro extends javax.swing.JInternalFrame {

    /**
     * Instancia eliminar carro
     */
    public ControlDeCarro controlador = ControlDeCarro.getInstanciaCarro();
    
    
    /**
     * Creates new form VentanaAgregarCarro
     */
    public VentanaEliminarCarro() {
        initComponents();
    }
    
    Carro carroAEliminar = new Carro();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarCarro = new javax.swing.JPanel();
        panelTitleEliminarCarro = new javax.swing.JPanel();
        lblTitleEliminarCarro = new javax.swing.JLabel();
        lblCarroABuscarElimianr = new javax.swing.JLabel();
        btnEliminarCarro = new javax.swing.JButton();
        txtCarroABuscarEliminar = new javax.swing.JTextField();
        btnCarroABuscarEliminar = new javax.swing.JButton();
        txtModeloEliminarCarro = new javax.swing.JTextField();
        txtPlacaEliminarCarro = new javax.swing.JTextField();
        txtCombustibleEliminarCarro = new javax.swing.JTextField();
        txtPuertasEliminarCarro = new javax.swing.JTextField();
        txtMarcaEliminarCarro = new javax.swing.JTextField();
        lblInstruccion = new javax.swing.JLabel();
        lblMarcaCarro = new javax.swing.JLabel();
        lblModeloCarro = new javax.swing.JLabel();
        lblPlacaCarro = new javax.swing.JLabel();
        lblCombustibleCarro = new javax.swing.JLabel();
        lblPuertasCarro = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        setResizable(true);

        panelEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        panelEliminarCarro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarCarro.setPreferredSize(new java.awt.Dimension(1150, 650));
        panelEliminarCarro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitleEliminarCarro.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleEliminarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleEliminarCarro.setText("ELIMINAR CARRO");

        javax.swing.GroupLayout panelTitleEliminarCarroLayout = new javax.swing.GroupLayout(panelTitleEliminarCarro);
        panelTitleEliminarCarro.setLayout(panelTitleEliminarCarroLayout);
        panelTitleEliminarCarroLayout.setHorizontalGroup(
            panelTitleEliminarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarCarroLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblTitleEliminarCarro)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        panelTitleEliminarCarroLayout.setVerticalGroup(
            panelTitleEliminarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleEliminarCarroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitleEliminarCarro)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelEliminarCarro.add(panelTitleEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 100));

        lblCarroABuscarElimianr.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblCarroABuscarElimianr.setForeground(new java.awt.Color(255, 255, 255));
        lblCarroABuscarElimianr.setText("Ingrese placa del carro a buscar");
        panelEliminarCarro.add(lblCarroABuscarElimianr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 380, 60));

        btnEliminarCarro.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminarCarro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCarro.setText("ELIMINAR");
        btnEliminarCarro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminarCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCarroActionPerformed(evt);
            }
        });
        panelEliminarCarro.add(btnEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 190, 80));

        txtCarroABuscarEliminar.setBackground(new java.awt.Color(255, 255, 255));
        txtCarroABuscarEliminar.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtCarroABuscarEliminar.setForeground(new java.awt.Color(0, 0, 0));
        txtCarroABuscarEliminar.setBorder(null);
        panelEliminarCarro.add(txtCarroABuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 230, 40));

        btnCarroABuscarEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnCarroABuscarEliminar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnCarroABuscarEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnCarroABuscarEliminar.setText("BUSCAR");
        btnCarroABuscarEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCarroABuscarEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarroABuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroABuscarEliminarActionPerformed(evt);
            }
        });
        panelEliminarCarro.add(btnCarroABuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 130, 40));

        txtModeloEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        txtModeloEliminarCarro.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtModeloEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        txtModeloEliminarCarro.setBorder(null);
        panelEliminarCarro.add(txtModeloEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 230, 30));

        txtPlacaEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        txtPlacaEliminarCarro.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPlacaEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        txtPlacaEliminarCarro.setBorder(null);
        panelEliminarCarro.add(txtPlacaEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 230, 30));

        txtCombustibleEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        txtCombustibleEliminarCarro.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtCombustibleEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        txtCombustibleEliminarCarro.setBorder(null);
        panelEliminarCarro.add(txtCombustibleEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 230, 30));

        txtPuertasEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        txtPuertasEliminarCarro.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPuertasEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        txtPuertasEliminarCarro.setBorder(null);
        panelEliminarCarro.add(txtPuertasEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 230, 30));

        txtMarcaEliminarCarro.setBackground(new java.awt.Color(51, 51, 51));
        txtMarcaEliminarCarro.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtMarcaEliminarCarro.setForeground(new java.awt.Color(255, 255, 255));
        txtMarcaEliminarCarro.setBorder(null);
        panelEliminarCarro.add(txtMarcaEliminarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 230, 30));

        lblInstruccion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Datos del carro que desea eliminar:");
        panelEliminarCarro.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 430, -1));

        lblMarcaCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblMarcaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblMarcaCarro.setText("Marca:");
        panelEliminarCarro.add(lblMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, -1));

        lblModeloCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblModeloCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblModeloCarro.setText("Modelo:");
        panelEliminarCarro.add(lblModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, -1));

        lblPlacaCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPlacaCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaCarro.setText("Placa:");
        panelEliminarCarro.add(lblPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 70, -1));

        lblCombustibleCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblCombustibleCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblCombustibleCarro.setText("Combustible:");
        panelEliminarCarro.add(lblCombustibleCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, -1));

        lblPuertasCarro.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        lblPuertasCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblPuertasCarro.setText("No. de puertas:");
        panelEliminarCarro.add(lblPuertasCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarroABuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroABuscarEliminarActionPerformed
        // TODO add your handling code here:
        carroAEliminar = controlador.verCarro(txtCarroABuscarEliminar.getText());
        txtMarcaEliminarCarro.setText(carroAEliminar.getMarca());
        txtModeloEliminarCarro.setText(carroAEliminar.getModelo());
        txtPlacaEliminarCarro.setText(carroAEliminar.getPlaca());
        txtCombustibleEliminarCarro.setText(carroAEliminar.getCombustible());
        txtPuertasEliminarCarro.setText(String.valueOf(carroAEliminar.getPuertas()));        
    }//GEN-LAST:event_btnCarroABuscarEliminarActionPerformed

    private void btnEliminarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCarroActionPerformed
        // TODO add your handling code here:
        controlador.eliminarCarro(carroAEliminar);
        setVisible(false);
        txtMarcaEliminarCarro.setText("");
        txtModeloEliminarCarro.setText("");
        txtPlacaEliminarCarro.setText("");
        txtCombustibleEliminarCarro.setText("");
        txtPuertasEliminarCarro.setText("");
        txtCarroABuscarEliminar.setText("");      
    }//GEN-LAST:event_btnEliminarCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarroABuscarEliminar;
    private javax.swing.JButton btnEliminarCarro;
    private javax.swing.JLabel lblCarroABuscarElimianr;
    private javax.swing.JLabel lblCombustibleCarro;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JLabel lblPuertasCarro;
    private javax.swing.JLabel lblTitleEliminarCarro;
    private javax.swing.JPanel panelEliminarCarro;
    private javax.swing.JPanel panelTitleEliminarCarro;
    private javax.swing.JTextField txtCarroABuscarEliminar;
    private javax.swing.JTextField txtCombustibleEliminarCarro;
    private javax.swing.JTextField txtMarcaEliminarCarro;
    private javax.swing.JTextField txtModeloEliminarCarro;
    private javax.swing.JTextField txtPlacaEliminarCarro;
    private javax.swing.JTextField txtPuertasEliminarCarro;
    // End of variables declaration//GEN-END:variables
}
