package org.oscarmorales.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.oscarmorales.controlador.ControlDeCamioneta;
import org.oscarmorales.modelo.Camioneta;

/**
 * Ventana ver camioneta
 * @author Oscar
 */
public class VentanaVerCamioneta extends javax.swing.JInternalFrame {

    /**
     * Instancia ver camioneta
     */
    public ControlDeCamioneta controlador = ControlDeCamioneta.getInstanciaCamioneta();
    
    /**
     * Creates new form VentanaVerCarro
     */
    public VentanaVerCamioneta() {
        initComponents();
    }

    /**
     * Metodo mostrar camioneta
     */
    public void mostrarCamioneta(){
        String [] encabezados = {"Marca","Modelo","Placa","Combustible","No. de asientos"};
        int cantidadDeCamionetas = controlador.cantidadDeCamionetas();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeCamionetas);
        tablaDeCamioneta.setModel(cabecera);
        TableModel listaDeCamionetas = tablaDeCamioneta.getModel();
        for(int i=0; i<cantidadDeCamionetas; i++){
            Camioneta camioneta = controlador.mostrarCamionetas().get(i);
            listaDeCamionetas.setValueAt(camioneta.getMarca(), i, 0);
            listaDeCamionetas.setValueAt(camioneta.getModelo(), i, 1);
            listaDeCamionetas.setValueAt(camioneta.getPlaca(), i, 2);
            listaDeCamionetas.setValueAt(camioneta.getCombustible(), i, 3);
            listaDeCamionetas.setValueAt(camioneta.getAsientos(), i, 4);
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVistaVerCamioneta = new javax.swing.JScrollPane();
        tablaDeCamioneta = new javax.swing.JTable();
        panelTitleAgregarCamioneta = new javax.swing.JPanel();
        lblTitleIAgregarCamioneta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1164, 676));

        tablaDeCamioneta.setBackground(new java.awt.Color(51, 51, 51));
        tablaDeCamioneta.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tablaDeCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        tablaDeCamioneta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Placa", "Combustible", "No. de asientos"
            }
        ));
        tablaDeCamioneta.setSelectionBackground(new java.awt.Color(0, 51, 51));
        tablaDeCamioneta.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollPanelVistaVerCamioneta.setViewportView(tablaDeCamioneta);

        panelTitleAgregarCamioneta.setBackground(new java.awt.Color(0, 102, 102));

        lblTitleIAgregarCamioneta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitleIAgregarCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleIAgregarCamioneta.setText("VER CAMIONETA");

        javax.swing.GroupLayout panelTitleAgregarCamionetaLayout = new javax.swing.GroupLayout(panelTitleAgregarCamioneta);
        panelTitleAgregarCamioneta.setLayout(panelTitleAgregarCamionetaLayout);
        panelTitleAgregarCamionetaLayout.setHorizontalGroup(
            panelTitleAgregarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleAgregarCamionetaLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(lblTitleIAgregarCamioneta)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        panelTitleAgregarCamionetaLayout.setVerticalGroup(
            panelTitleAgregarCamionetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleAgregarCamionetaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblTitleIAgregarCamioneta)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitleAgregarCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelVistaVerCamioneta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitleAgregarCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelVistaVerCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitleIAgregarCamioneta;
    private javax.swing.JPanel panelTitleAgregarCamioneta;
    private javax.swing.JScrollPane scrollPanelVistaVerCamioneta;
    private javax.swing.JTable tablaDeCamioneta;
    // End of variables declaration//GEN-END:variables
}
